### ISSUE TITLE
Add an app icon

### ISSUE THREAD

**Issue by ryonakano** [ryonakano/louper#1]

**Comment by hanaral** [comment]
Any ideas for a theme? I think the magnifying glass thing is a bit overdone, but it could still work

**Comment by ryonakano** [comment]
Hi @hanaral, thanks for getting interested in this project. I think an icon that motifs the magnifying glass would be simple and easy-to-understand what this app does for users.

**Comment by hanaral** [comment]
一所懸命働いて作ったよ。
This is literally just the 64px variant, I'm going to have to skimp out on the effects unless I want the smaller sizes to be completely inaccessible.
![com github cleac olifant](https://user-images.githubusercontent.com/58219504/108571019-19380880-7307-11eb-9fd5-9415290e62cd.png)

**Comment by ryonakano** [comment]
おー！　ありがとうございます！
I didn't expect that I saw the historical term "突厥文字" out of the world history class :rofl: Really looks nice!

One thing that I wonder is that if we should use the round for the zoomed object itself; currently we have two rounds—the magnifier and the base object. I feel like it's fine that the magnifier uses the round but the base object can be a rectangle instead, like this (sorry for my poor drawing :sweat_smile:):

![IMG_0876 2](https://user-images.githubusercontent.com/26003928/108578409-ed983b00-7365-11eb-9c36-8b6f44cf553e.jpeg)

**Comment by hanaral** [comment]
じゃぁ、こうしていかがですか？
![com github ryonakano louper](https://user-images.githubusercontent.com/58219504/108603532-5d2b1c00-73a0-11eb-9774-d31f5a51f153.png)
It looks quite a bit more balanced this way, although I initially wanted to use rounded corners on the rectangle it turns out it doesn't look so great at 64px

**Comment by ryonakano** [comment]
Looks good! Would you create that icon in other pixels like 128px and create a pull request?

**Comment by hanaral** [comment]
オワッタァァァァァ！
I fixed some of the issues to do with the shape's sizes too!

**Comment by ryonakano** [comment]
Hi @hanaral, really big thank you for working on this!! :tada:
